### ISSUE TITLE
Leaked Groq Key

### ISSUE THREAD

**Issue by jacobweiss2305** [groq/groq-api-cookbook#30]
Is the api key in this notebook meant to be hardcoded:
crewai-mixture-of-agents/Mixture-of-Agents-Crew-AI-Groq.ipynb

**Comment by hozen-groq** [comment]
Hi, Jacob! Appreciate you checking out our Groq API Cookbook. That most definitely wasn't meant to be hardcoded... thank you for letting us know! 🥲
