### ISSUE TITLE
Colab on YouTube Video

### ISSUE THREAD

**Issue by jacobweiss2305** [groq/groq-api-cookbook#36]
Hey @hozen-groq , 

Curious if we can colaborate on a Youtube Video:
https://www.youtube.com/@GroqInc/featured

Shoot me an email:
jaweiss2305@gmail.com
jacob.weiss@phidata.com

Similiar to this one:
https://www.youtube.com/watch?v=Q3fh0sWVRX4&t

**Comment by hozen-groq** [comment]
Great idea! Connecting with you via email now.
