### ISSUE TITLE
Git clone issues on Windows

### ISSUE THREAD

**Issue by Mustafa-Esoofally** [groq/groq-api-cookbook#49]
> git reset -q HEAD -- .
error: invalid path 'tutorials/toolhouse-for-tool-use-with-groq-api/Groq <> Toolhouse.ipynb'
fatal: make_cache_entry failed for path 'tutorials/toolhouse-for-tool-use-with-groq-api/Groq <> Toolhouse.ipynb'

**Comment by hozen-groq** [comment]
I believe the full path should begin with `groq/groq-api-cookbook/tutorials`.

**Comment by Mustafa-Esoofally** [comment]
I think the problem is with the  name of the file Groq <> Toolhouse.ipynb
