### ISSUE TITLE
FEATURE REQUEST: Primed completion

### ISSUE THREAD

**Issue by RomanKoshkin** [groq/groq-api-cookbook#7]
Suppose the model is Mistral, and its prompt format is 
```
<s> [INST] Instruction [/INST] Model answer</s> [INST] Follow-up instruction [/INST]
```

and suppose I want the assistant model to start its response with the phrase I want, e.g. the word "Take". If I make a request to the Groq API with

```
messages = [
{"role": "user", "How do I make coffee?"}, 
{"role": "assistant", "Take"}]
```

it gets formatted into

```
<s> [INST] How do I make coffee? [/INST] Take </s>
```

I want an option to NOT append the EOS token to the user-provided assistant's message. In other words, what I want is for Groq to generate a completion starting from a user-provided prefix like so:

```
<s> [INST] How do I make coffee? [/INST] Take
```

so that the full response would be 

```
<s> [INST] How do I make coffee? [/INST] Take good coffee beans and boil...
```

**Comment by hozen-groq** [comment]
Hi there, @RomanKoshkin! Appreciate the level of detail here and just want to let you know that I've brought this back to our engineering/product teams as a feature request. Hopefully the team can look into it. 

In the meantime, if you haven't already, I highly recommend joining our [developer community on Discord](https://discord.gg/groq) - we are pretty active there and the community will be the first to know about any new features/updates! 😁
